// Application UI
export const SET_THEME = 'SET_THEME' 
// User 
export const SET_USER_PROFILE = 'SET_USER_PROFILE' 
export const UPDATE_PROFILE = 'UPDATE_PROFILE' 
export const ADD_NEW_NOTE = 'ADD_NEW_NOTE' 
export const SEARCH_EVENTS = 'SEARCH_EVENTS' 
export const STOCK_EVENTS = 'STOCK_EVENTS' 
export const RESET_SEARCH_EVENTS= 'RESET_SEARCH_EVENTS'
export const SET_LOADING = 'SET_LOADING' 
export const SET_USER_PROFILE_EVENT= 'SET_USER_PROFILE_EVENT'